############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Features"
url = "#features"
weight = 2

[[main]]
name = "FAQ"
url = "#faq"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4

[[main]]
name = "About"
url = "/about"
weight = 5

# footer menu
[[footer]]
name = "Contact"
url = "/contact"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2
